# Generated by Django 5.2.17 on 2026-09-01 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('code_acces', models.CharField(max_length=50, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('creche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='creches.creche')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Emargement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_event', models.CharField(choices=[('ARRIVEE', 'Arrivée'), ('DEPART', 'Départ'), ('PAUSE_DEBUT', 'Début de pause'), ('PAUSE_FIN', 'Fin de pause')], max_length=20)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('signature', models.TextField()),
                ('creche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emargements', to='creches.creche')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emargements', to='creches.employee')),
            ],
            options={
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['employee', 'horodatage'], name='creches_ema_employe_24d255_idx')],
            },
        ),
    ]
