# Generated by Django 6.1 on 2026-09-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='heures_jour_contrat',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Heures de travail prévues par jour (ex: 7.0 pour 35h/semaine)', max_digits=4),
        ),
    ]
