# Generated by Django 6.1 on 2026-09-02 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0002_employee_heures_jour_contrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('matin_debut', models.TimeField(blank=True, null=True)),
                ('matin_fin', models.TimeField(blank=True, null=True)),
                ('aprem_debut', models.TimeField(blank=True, null=True)),
                ('aprem_fin', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='creches.employee')),
            ],
            options={
                'ordering': ['jour'],
                'unique_together': {('employee', 'jour')},
            },
        ),
    ]
