# Generated by Django 6.1 on 2026-09-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0003_employeeschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emargement',
            name='type_event',
            field=models.CharField(choices=[('ARRIVEE', 'Arrivée'), ('DEPART', 'Départ')], max_length=20),
        ),
    ]
